## HeadPermutations / v1

Find permutations of A in ABCD / use For Loop

In [15]:
def head_permutations(s):

    head = s[0]
    tail = s[1:]
    #print(head, tail)

    P = []
    for i in range(len(tail) + 1):
        new_head = tail[0:i]
        new_tail = tail[i:]     
        #print(" "*i, new_head, new_tail)

        permutation = new_head + head + new_tail        
        #print(permutation)
        
        P.append(permutation)
    return P

P = head_permutations('ABCD')
print(P)

['ABCD', 'BACD', 'BCAD', 'BCDA']


## HeadPermutations / v2

Find permutations of A in ABCD / use List Comprehension

In [16]:
def head_permutations_v2(s):
    head = s[0]
    tail = s[1:]
    P = [tail[0:i] + head + tail[i:] for i in range(len(tail) + 1)]
    return P

P = head_permutations_v2('123456')
print(P)

['123456', '213456', '231456', '234156', '234516', '234561']


## Permutations / v1

Find permutations (without repetition) of ABCD / use Recursion

In [17]:
def permutations(s):

    if len(s) == 1: 
        return s # Base case
        
    head = s[0]
    tail = s[1:]

    P = []
    for ss in permutations(tail):
        for i in range(len(ss) + 1):
            prm = ss[0:i] + head + ss[i:]
            P.append(prm)

    return P

P = permutations('ABC')
print(P)

['ABC', 'BAC', 'BCA', 'ACB', 'CAB', 'CBA']


## Permutations / v2

Find permutations (without repetition) of 12345 / use Recursion / use List Comprehension

In [18]:
def permutations(s):

    if len(s) == 1: 
        return s # Base case
        
    head = s[0]
    tail = s[1:]

    P = []
    for w in permutations(tail):
        W = [w[0:i] + head + w[i:] for i in range(len(w) + 1)]
        P = P + W

    return P

P = permutations('1234')
print(P)

import math
assert len(P) == math.factorial(4)

['1234', '2134', '2314', '2341', '1324', '3124', '3214', '3241', '1342', '3142', '3412', '3421', '1243', '2143', '2413', '2431', '1423', '4123', '4213', '4231', '1432', '4132', '4312', '4321']


## Permuations / v3

Find permutations (without repetition) of 1234 / use Itertools library

In [19]:
import math
import itertools

P = itertools.permutations('1234')
P = list(P)
P = [''.join(x) for x in P]

print(list(P))
assert len(P) == math.factorial(4)

['1234', '1243', '1324', '1342', '1423', '1432', '2134', '2143', '2314', '2341', '2413', '2431', '3124', '3142', '3214', '3241', '3412', '3421', '4123', '4132', '4213', '4231', '4312', '4321']


## k-Combinations / v1

Find 2-Combinations and 3-Combinations (without repetition) of ABCD / use Recursion

In [27]:
def combinations(s, k):
    C = []

    if len(s) == k: # Base case
        return [s]

    head = s[:1]
    tail = s[1:]
    # print(head, tail)

    # Combinations that include the head
    C1 = []
    for i in range(len(tail)):
        
        right = tail[i:i+k-1] # 1 for the head
        # print(right)

        if len(right) == k-1:
            combination = head + right
            C1.append(combination)
            
    #print(C1)
    
    # Combinations without the head
    C2 = combinations(tail, k)

    #print(C2)

    C = C1 + C2    
    return C

C = combinations('ABCD', 2)
print(C)

C = combinations('ABCD', 3)
print(C)

['AB', 'AC', 'AD', 'BC', 'BD', 'CD']
['ABC', 'ACD', 'BCD']


## k-Combinations / v2

Find k-Combinations (without repetition) of ABCD  / use Recursion / use List Comprehension

In [21]:
def combinations(s, k):

    # Base case
    if k == 0:  return ['']
    if s == '': return []

    head = s[:1]
    tail = s[1:]
    
    # Combintations that include the head
    C1 = [head + c for c in combinations(tail, k-1)]

    # Combinations without the head
    C2 = combinations(tail, k)

    return C1 + C2

C = combinations('123456', 4)
print(C)

import math
assert len(C) == math.comb(6, 4)

['1234', '1235', '1236', '1245', '1246', '1256', '1345', '1346', '1356', '1456', '2345', '2346', '2356', '2456', '3456']


## k-Combinations / v3

Find k-Combinations (without repetition) of 123456 / use Itertools

In [31]:
import math
import itertools

C = itertools.combinations('123456', 4)
C = list(C)
C = [''.join(c) for c in C]

print(C)
assert len(C) == math.comb(6, 4)

['1234', '1235', '1236', '1245', '1246', '1256', '1345', '1346', '1356', '1456', '2345', '2346', '2356', '2456', '3456']
